# This file allows Apache to help us automatically update the website,
# when we push a commit to https://github.com/apache/creadur-site
publish:
  whoami: asf-site
  
github:
  description: "Apache Creadur website"
  homepage: https://creadur.apache.org/
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: false
notifications:
  commits: commits@creadur.apache.org

