# This file allows Apache to help us automatically update the website,
# when we push a commit to https://github.com/apache/creadur-site
publish:
  whoami: asf-site

github:
  description: "Apache Creadur website"
  homepage: https://creadur.apache.org/
  del_branch_on_merge: true
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: false

  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
          - "release/*"
          - "rel/*"
        excludes: []
      bypass_teams:
        - root
      restrict_deletion: true
      restrict_force_push: true
notifications:
  commits: commits@creadur.apache.org
